import React from 'react'

function About() {
  return (
    <div className="about">
        <h4 className="title">About</h4>
        <p className="about-para">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium exercitationem placeat veritatis iste minus, quod quisquam sunt ullam hic tempore asperiores est ut non voluptatibus ad voluptas nesciunt. Odit excepturi labore, temporibus perferendis libero optio hic animi quas cupiditate vitae dolore! Exercitationem iste nemo eos error reiciendis beatae distinctio officia rerum, repellat cupiditate accusamus fuga molestias illum praesentium sequi vero repellendus a voluptatem. Amet omnis rem nobis incidunt itaque repellendus quaerat soluta corporis distinctio, alias in quae dicta nam illum laborum suscipit quasi possimus debitis tenetur quis. Provident quas reprehenderit aspernatur, iste exercitationem illo totam assumenda error dicta nobis voluptatem voluptates inventore. Corrupti dignissimos sed, tempore modi voluptate officiis inventore incidunt ducimus nulla molestias quidem. Illo aliquam repudiandae voluptatem temporibus veniam, repellendus distinctio explicabo in ad deserunt mollitia assumenda excepturi quisquam culpa quos doloribus esse. Dolorum, rerum quod omnis tempora velit ex doloribus nam, voluptates ab eveniet corrupti odio labore odit aspernatur temporibus. Laboriosam repellendus eligendi iure ex deleniti at cumque excepturi tempora laborum expedita, quibusdam, quam sapiente iusto ipsam ut quas nam quos optio, officia minus reiciendis labore sequi deserunt. Beatae praesentium, consequuntur libero alias rem, fuga adipisci impedit illum culpa, ullam provident maxime vero error itaque ab eligendi.</p>
     
            <p className="about-para">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium exercitationem placeat veritatis iste minus, quod quisquam sunt ullam hic tempore asperiores est ut non voluptatibus ad voluptas nesciunt. Odit excepturi labore, temporibus perferendis libero optio hic animi quas cupiditate vitae dolore! Exercitationem iste nemo eos error reiciendis beatae distinctio officia rerum, repellat cupiditate accusamus fuga molestias illum praesentium sequi vero repellendus a voluptatem. Amet omnis rem nobis incidunt itaque repellendus quaerat soluta corporis distinctio, alias in quae dicta nam illum laborum suscipit quasi possimus debitis tenetur quis. Provident quas reprehenderit aspernatur, iste exercitationem illo totam assumenda error dicta nobis voluptatem voluptates inventore. Corrupti dignissimos sed, tempore modi voluptate officiis inventore incidunt ducimus nulla molestias quidem. Illo aliquam repudiandae voluptatem temporibus veniam, repellendus distinctio explicabo in ad deserunt mollitia assumenda excepturi quisquam culpa quos doloribus esse. Dolorum, rerum quod omnis tempora velit ex doloribus nam, voluptates ab eveniet corrupti odio labore odit aspernatur temporibus. Laboriosam repellendus eligendi iure ex deleniti at cumque excepturi tempora laborum expedita, quibusdam, quam sapiente iusto ipsam ut quas nam quos optio, officia minus reiciendis labore sequi deserunt. Beatae praesentium, consequuntur libero alias rem, fuga adipisci impedit illum culpa, ullam provident maxime vero error itaque ab eligendi.</p>
     
        </div>
  )
}

export default About